<?php

namespace Rpgmr\RpgmrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampanhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampanhaRepository extends EntityRepository
{
}