<?php

namespace Rpgmr\RpgmrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DescricaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescricaoRepository extends EntityRepository
{
}
